inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snippets from READMEs.
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'bin/*'
    - 'config/environments/*.rb'
    - 'Brewfile'

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

RSpec/ExampleLength:
  Max: 11

RSpec/IndexedLet:
  Enabled: false
