---
openapi: 3.0.1
info:
  title: Complexity of Need API
  version: v1
  description: |
    A microservice which holds the Complexity of Need level associated with offenders

    ### Authentication

    This API is secured by OAuth 2 with tokens supplied by HMPPS Auth.

    Read permissions are granted to clients with the role `ROLE_COMPLEXITY_OF_NEED`

    Write permissions are granted to clients with the role `ROLE_UPDATE_COMPLEXITY_OF_NEED`.

    ---

    Owned by the **Manage POM Cases** team

    - Slack: [#manage-pom-cases](https://mojdt.slack.com/channels/manage-pom-cases)
    - GitHub: [ministryofjustice/hmpps-complexity-of-need](https://github.com/ministryofjustice/hmpps-complexity-of-need)
security:
- HmppsAuth:
  - read
components:
  securitySchemes:
    HmppsAuth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://hmpps_oauth_service.com'
          scopes:
            'write:CL': write CL entries
            'read:CL': read CL entries
  schemas:
    Level:
      type: string
      enum:
      - low
      - medium
      - high
      description: Complexity of Need Level
      example: low
    OffenderNo:
      type: string
      description: NOMIS Offender Number
      example: A0000AA
    ComplexityOfNeed:
      type: object
      properties:
        offenderNo:
          "$ref": "#/components/schemas/OffenderNo"
        level:
          "$ref": "#/components/schemas/Level"
        sourceUser:
          type: string
          description: The NOMIS username that supplied this Complexity of Need entry
          example: JSMITH_GEN
        sourceSystem:
          type: string
          description: The OAuth Client ID of the system that created this entry
          example: hmpps-api-client-id
        notes:
          type: string
          description: Free-text notes for this entry
        createdTimeStamp:
          type: string
          format: date_time
          description: The date & time this entry was created (in RFC 3339 format)
          example: '2021-03-02T17:18:46.457Z'
        active:
          type: boolean
          description: Whether it is active or not
      required:
      - offenderNo
      - level
      - createdTimeStamp
      - sourceSystem
      additionalProperties: false
    NewComplexityOfNeed:
      type: object
      properties:
        level:
          "$ref": "#/components/schemas/Level"
        sourceUser:
          type: string
          description: The NOMIS username that supplied this Complexity of Need entry
          example: JSMITH_GEN
        notes:
          type: string
          description: Free-text notes for this entry
      required:
      - level
      additionalProperties: false
tags:
- name: Single Offender
  description: Access Complexity of Need for a single offender
- name: Multiple Offenders
  description: Access Complexity of Need for multiple offenders at once
paths:
  "/complexity-of-need/offender-no/{offender_no}":
    parameters:
    - name: offender_no
      in: path
      description: NOMIS Offender Number
      example: A0000AA
      required: true
      schema:
        type: string
    get:
      summary: Retrieve the current Complexity of Need level for an offender
      tags:
      - Single Offender
      responses:
        '200':
          description: Offender's current Complexity of Need level found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ComplexityOfNeed"
        '401':
          description: Invalid or missing access token
        '403':
          description: Access token is missing scope `read`
        '404':
          description: The Complexity of Need level for this offender is not known
    post:
      summary: Update the Complexity of Need level for an offender
      tags:
      - Single Offender
      description: 'Clients calling this endpoint must have role: `ROLE_UPDATE_COMPLEXITY_OF_NEED`'
      parameters: []
      responses:
        '200':
          description: Complexity of Need level set successfully
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ComplexityOfNeed"
        '400':
          description: There were validation errors. Make sure you've given a valid
            level.
        '401':
          description: Invalid or missing access token
        '403':
          description: Access token is missing role `ROLE_COMPLEXITY_OF_NEED` or scope
            `write`
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/NewComplexityOfNeed"
  "/complexity-of-need/multiple/offender-no":
    post:
      summary: Retrieve the current Complexity of Need levels for multiple offenders
      tags:
      - Multiple Offenders
      description: |
        This endpoint returns a JSON array containing the current Complexity of Need entry for multiple offenders.

        The response array:
          - will exclude offenders whose Complexity of Need level is not known (i.e. these would result in a `404 Not Found` error on the single `GET` endpoint)
          - is not sorted in the same order as the request body
          - is not paginated
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ComplexityOfNeed"
        '400':
          description: The request body was invalid. Make sure you've provided a JSON
            array of NOMIS Offender Numbers.
        '401':
          description: Invalid or missing access token
        '403':
          description: Access token is missing scope `read`
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                "$ref": "#/components/schemas/OffenderNo"
              description: A JSON array of NOMIS Offender Numbers
              example:
              - A0000AA
              - B0000BB
              - C0000CC
  "/complexity-of-need/offender-no/{offender_no}/history":
    parameters:
    - name: offender_no
      in: path
      description: NOMIS Offender Number
      example: A0000AA
      required: true
      schema:
        type: string
    get:
      summary: Retrieve full history of Complexity of Needs for an offender
      tags:
      - Single Offender
      description: Results are sorted chronologically (newest first, oldest last)
      responses:
        '200':
          description: Offender's Complexity of Need history found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ComplexityOfNeed"
        '401':
          description: Invalid or missing access token
        '403':
          description: Access token is missing scope `read`
        '404':
          description: The Complexity of Need level for this offender is not known
  "/complexity-of-need/offender-no/{offender_no}/inactivate":
    parameters:
    - name: offender_no
      in: path
      description: NOMIS Offender Number
      example: A0000AA
      required: true
      schema:
        type: string
    put:
      summary: Inactivate the Complexity of Need level for an offender
      tags:
      - Single Offender
      description: 'Clients calling this endpoint must have role: `ROLE_UPDATE_COMPLEXITY_OF_NEED`'
      responses:
        '200':
          description: Complexity of Need level inactivated successfully
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ComplexityOfNeed"
        '401':
          description: Invalid or missing access token
        '403':
          description: Access token is missing role `ROLE_COMPLEXITY_OF_NEED` or scope
            `write`
servers:
- url: https://complexity-of-need-staging.hmpps.service.justice.gov.uk/v1
  description: Staging/dev environment
- url: https://complexity-of-need-preprod.hmpps.service.justice.gov.uk/v1
  description: Pre-production environment
- url: https://complexity-of-need.hmpps.service.justice.gov.uk/v1
  description: Production environment

