references:
  defaults: &defaults
    working_directory: ~/repo

  github_team_name_slug: &github_team_name_slug
    GITHUB_TEAM_NAME_SLUG: offender-management
    QUAYIO_REPO: quay.io/hmpps/hmpps-complexity-of-need
    REPONAME: hmpps-complexity-of-need

  deploy_container_config: &deploy_container_config
    resource_class: small
    docker:
      - image: ministryofjustice/cloud-platform-tools
        environment:
          KUBE_ENV_STAGING_NAMESPACE: hmpps-complexity-of-need-staging
          KUBE_ENV_PREPROD_NAMESPACE: hmpps-complexity-of-need-preprod
          KUBE_ENV_PRODUCTION_NAMESPACE: hmpps-complexity-of-need-production

  test_container_config: &test_container_config
    resource_class: small
    docker:
      - image: cimg/ruby:3.3.3
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: ubuntu
          RACK_ENV: test
          AWS_DEFAULT_REGION: eu-west-2
          NOMIS_OAUTH_HOST: https://test-auth-service.example.com
          NOMIS_OAUTH_CLIENT_ID: test-client-id
          MOCK_AUTH: 1
      - image: circleci/postgres:10.5-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: hmpps_complexity_of_need_test

  install_gpg: &install_gpg
    run:
      name: Install GPG
      command: |
        apk add \
          --no-cache \
          --no-progress \
          gnupg

  configure_gpg: &configure_gpg
    run:
      name: Configure GPG
      command: |
        echo "${GPG_PRIVATE_KEY}" | base64 -d | gpg --batch --allow-secret-key-import --import

  decrypt_secrets: &decrypt_secrets
    run:
      name: Decrypt secrets file
      command: |
        gpg --export-ownertrust > /tmp/ownertrust.txt
        echo $GPG_KEY_ID:1 >> /tmp/ownertrust.txt
        gpg --import-ownertrust /tmp/ownertrust.txt
        gpgconf --kill gpg-agent
        gpg-agent --daemon --allow-preset-passphrase
        /usr/libexec/gpg-preset-passphrase --preset --passphrase $GPG_PASSPHRASE $GPG_KEY_KEYGRIP_ID
        git-crypt unlock

  install_aws_cli: &install_aws_cli
    run:
      name: Set up aws
      command: |
        sudo apt-get update
        sudo apt-get --assume-yes install python3-pip
        sudo pip3 install awscli

  install_yq: &install_yq
    run:
      name: Install yq (YAML parser)
      command: |
        wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - |\
        tar xz && mv ${BINARY} /usr/bin/yq
      environment:
        VERSION: v4.6.3
        BINARY: yq_linux_amd64

  build_docker_image: &build_docker_image
    run:
      name: Build docker image
      command: |
        export BUILD_DATE=$(date -Is) >> $BASH_ENV
        source $BASH_ENV
        docker build \
          --build-arg VERSION_NUMBER=${CIRCLE_BUILD_NUM} \
          --build-arg COMMIT_ID=${CIRCLE_SHA1} \
          --build-arg BUILD_DATE=${BUILD_DATE} \
          --build-arg BUILD_TAG=${CIRCLE_BRANCH} \
          -t app .

  push_docker_image: &push_docker_image
    run:
      name: Push docker image
      command: |
        set -xeuo pipefail
        docker login --username "${QUAYIO_USERNAME}" --password "${QUAYIO_PASSWORD}" quay.io
        docker tag app "${QUAYIO_REPO}:${CIRCLE_SHA1}"
        docker push "${QUAYIO_REPO}:${CIRCLE_SHA1}"

        if [ "${CIRCLE_BRANCH}" == "main" ]; then
          docker tag app "${QUAYIO_REPO}:latest"
          docker push "${QUAYIO_REPO}:latest"
        fi
      environment:
        <<: *github_team_name_slug

version: 2.1

orbs:
  ruby: circleci/ruby@2.1.3
  hmpps: ministryofjustice/hmpps@9.1.0

jobs:
  install_dependencies:
    <<: *defaults
    <<: *test_container_config
    steps:
      - checkout
      - ruby/install-deps

  rubocop:
    <<: *defaults
    <<: *test_container_config
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check

  run_tests:
    <<: *defaults
    <<: *test_container_config
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Security analysis
          command: bundle exec brakeman -o ~/test-results/brakeman/brakeman.json -o ~/test-results/brakeman/brakeman.html
      - ruby/rspec-test

  build_and_push_docker_image:
    <<: *defaults
    <<: *test_container_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - *install_aws_cli
      - *build_docker_image
      - *push_docker_image

  deploy_staging:
    <<: *deploy_container_config
    steps:
      - checkout
      - run:
          name: Kubectl deployment to live cluster staging setup
          command: |
            echo -n ${CLUSTER_LIVE_CERT} | base64 -d > ./live_ca.crt
            kubectl config set-cluster ${CLUSTER_NAME_LIVE} --certificate-authority=./live_ca.crt --server=https://${CLUSTER_NAME_LIVE}
            kubectl config set-credentials circleci --token=${LIVE_STAGING_TOKEN}
            kubectl config set-context ${CLUSTER_NAME_LIVE} --cluster=${CLUSTER_NAME_LIVE} --user=circleci --namespace=${KUBE_ENV_STAGING_NAMESPACE}
            kubectl config use-context ${CLUSTER_NAME_LIVE}
            kubectl config current-context
            kubectl --namespace=${KUBE_ENV_STAGING_NAMESPACE} get pods
      - *install_gpg
      - *configure_gpg
      - *decrypt_secrets
      - *install_yq
      - run:
          name: Deploy to staging
          command: |
            kubectl delete job hmpps-complexity-of-need-migration --ignore-not-found
            sed -i -e s/:latest/:$CIRCLE_SHA1/ deploy/staging/deployment.yaml
            sed -i -e s/:latest/:$CIRCLE_SHA1/ deploy/staging/migration-job.yaml
            kubectl apply --record=false -f ./deploy/staging
            kubectl annotate deployments/hmpps-complexity-of-need kubernetes.io/change-cause="$CIRCLE_BUILD_URL"
          environment:
            <<: *github_team_name_slug
      - run:
          name: Wait for Kube to spin up new pods
          command: bash .circleci/wait-for-successful-deployment.sh "$KUBE_ENV_STAGING_NAMESPACE" "hmpps-complexity-of-need" "$CIRCLE_SHA1"

  deploy_preprod:
    <<: *deploy_container_config
    steps:
      - checkout
      - run:
          name: Kubectl deployment preprod setup
          command: |
            echo -n ${CLUSTER_LIVE_CERT} | base64 -d > ./live_ca.crt
            kubectl config set-cluster ${CLUSTER_NAME_LIVE} --certificate-authority=./live_ca.crt --server=https://${CLUSTER_NAME_LIVE}
            kubectl config set-credentials circleci --token=${LIVE_PREPROD_TOKEN}
            kubectl config set-context ${CLUSTER_NAME_LIVE} --cluster=${CLUSTER_NAME_LIVE} --user=circleci --namespace=${KUBE_ENV_PREPROD_NAMESPACE}
            kubectl config use-context ${CLUSTER_NAME_LIVE}
            kubectl config current-context
            kubectl --namespace=${KUBE_ENV_PREPROD_NAMESPACE} get pods
      - *install_gpg
      - *configure_gpg
      - *decrypt_secrets
      - *install_yq
      - run:
          name: Deploy to pre-production
          command: |
            kubectl delete job rails-db-migration --ignore-not-found
            sed -i -e s/:latest/:$CIRCLE_SHA1/ deploy/preprod/deployment.yaml
            sed -i -e s/:latest/:$CIRCLE_SHA1/ deploy/preprod/migration-job.yaml
            kubectl apply --record=false -f ./deploy/preprod
            kubectl annotate deployments/app-deployment kubernetes.io/change-cause="$CIRCLE_BUILD_URL"
          environment:
            <<: *github_team_name_slug
      - run:
          name: Wait for Kube to spin up new pods
          command: bash .circleci/wait-for-successful-deployment.sh "$KUBE_ENV_PREPROD_NAMESPACE" "hmpps-complexity-of-need" "$CIRCLE_SHA1"

  deploy_production:
    <<: *deploy_container_config
    steps:
      - checkout
      - run:
          name: Kubectl deployment production setup
          command: |
            echo -n ${CLUSTER_LIVE_CERT} | base64 -d > ./live_ca.crt
            kubectl config set-cluster ${CLUSTER_NAME_LIVE} --certificate-authority=./live_ca.crt --server=https://${CLUSTER_NAME_LIVE}
            kubectl config set-credentials circleci --token=${LIVE_PRODUCTION_TOKEN}
            kubectl config set-context ${CLUSTER_NAME_LIVE} --cluster=${CLUSTER_NAME_LIVE} --user=circleci --namespace=${KUBE_ENV_PRODUCTION_NAMESPACE}
            kubectl config use-context ${CLUSTER_NAME_LIVE}
            kubectl config current-context
            kubectl --namespace=${KUBE_ENV_PRODUCTION_NAMESPACE} get pods
      - *install_gpg
      - *configure_gpg
      - *decrypt_secrets
      - *install_yq
      - run:
          name: Deploy to production
          command: |
            kubectl delete job rails-db-migration --ignore-not-found
            sed -i -e s/:latest/:$CIRCLE_SHA1/ deploy/production/deployment.yaml
            sed -i -e s/:latest/:$CIRCLE_SHA1/ deploy/production/migration-job.yaml
            kubectl apply --record=false -f ./deploy/production
            kubectl annotate deployments/app-deployment kubernetes.io/change-cause="$CIRCLE_BUILD_URL"
          environment:
            <<: *github_team_name_slug
      - run:
          name: Wait for Kube to spin up new pods
          command: bash .circleci/wait-for-successful-deployment.sh "$KUBE_ENV_PRODUCTION_NAMESPACE" "hmpps-complexity-of-need" "$CIRCLE_SHA1"

workflows:
  build_and_test:
    jobs:
      - install_dependencies
      - rubocop:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - build_and_push_docker_image:
          requires:
            - rubocop
            - run_tests
          filters:
            branches:
              only:
                - main
                - preprod
      - deploy_staging:
          requires:
            - build_and_push_docker_image
          filters:
            branches:
              only:
                - main
      - deploy_production_approval:
          type: approval
          requires:
            - deploy_staging
          filters:
            branches:
              only: main
      - deploy_production:
          requires:
            - deploy_production_approval
          filters:
            branches:
              only: main
      - deploy_preprod:
          requires:
            - build_and_push_docker_image
          filters:
            branches:
              only: preprod
