default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hmpps_complexity_of_need_development

test:
  <<: *default
  database: hmpps_complexity_of_need_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_NAME'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host:     <%= ENV['POSTGRES_HOST'] %>
  sslmode: verify-full
  sslrootcert: /home/appuser/.postgresql/root.crt
