---
generic-prometheus-alerts:
  alertSeverity: mpc-alerts-nonprod-dev
  rdsAlertsDatabases:
    cloud-platform-030540d10be652c9: staging

generic-service:
  ingress:
    hosts:
      - complexity-of-need-staging.hmpps.service.justice.gov.uk
    tlsSecretName: staging-cert

  scheduledDowntime:
    enabled: true

  env:
    SENTRY_CURRENT_ENV: staging
    COMPLEXITY_OF_NEED_HOST: https://complexity-of-need-staging.hmpps.service.justice.gov.uk
    NOMIS_OAUTH_HOST: https://sign-in-dev.hmpps.service.justice.gov.uk
