---
generic-service:
  ingress:
    hosts:
      - complexity-of-need-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: preprod-cert

  env:
    SENTRY_CURRENT_ENV: preprod
    COMPLEXITY_OF_NEED_HOST: https://complexity-of-need-preprod.hmpps.service.justice.gov.uk
    NOMIS_OAUTH_HOST: https://sign-in-preprod.hmpps.service.justice.gov.uk
