---
generic-prometheus-alerts:
  rdsAlertsDatabases:
    cloud-platform-caf2be118f45c7ce: production

generic-service:
  alertSeverity: mpc-alerts-prod
  ingress:
    hosts:
      - complexity-of-need.hmpps.service.justice.gov.uk
    tlsSecretName: production-cert

  env:
    SENTRY_CURRENT_ENV: production
    COMPLEXITY_OF_NEED_HOST: https://complexity-of-need.hmpps.service.justice.gov.uk
    NOMIS_OAUTH_HOST: https://sign-in.hmpps.service.justice.gov.uk
