name: Pipeline [test -> build -> deploy]

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable or testing tags
        required: false
        default: ''
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm_lint:
    strategy:
      matrix:
        environments: ['staging', 'preprod', 'production']
    name: Helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RACK_ENV: test
      DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1/hmpps_complexity_of_need_test"
      AWS_DEFAULT_REGION: eu-west-2
      NOMIS_OAUTH_HOST: https://test-auth-service.example.com
      NOMIS_OAUTH_CLIENT_ID: test-client-id
      MOCK_AUTH: 1
    services:
      postgres:
        image: postgres:15.2-alpine
        env:
          POSTGRES_DB: hmpps_complexity_of_need_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup test database
        run: bin/rails db:prepare
      - name: Run brakeman
        run: bundle exec brakeman
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run rspec
        run: bundle exec rspec

  verify_docker_image:
    name: Verify docker image
    if: ${{ ! contains(fromJSON('["refs/heads/main", "refs/heads/staging"]'), github.ref) }}
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2 # WORKFLOW_VERSION
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      push: false
      docker_multiplatform: false

  build:
    name: Build docker image
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/staging"]'), github.ref) }}
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2 # WORKFLOW_VERSION
    needs:
      - helm_lint
      - test
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push || true }}
      docker_multiplatform: false

  deploy_staging:
    name: Deploy to staging
    needs:
      - build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'staging'
      app_version: '${{ needs.build.outputs.app_version }}'

  deploy_preprod:
    name: Deploy to preprod
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.build.outputs.app_version }}'

  deploy_production:
    name: Deploy to production
    needs:
      - deploy_preprod
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'production'
      app_version: '${{ needs.build.outputs.app_version }}'
      slack_notification: 'true'
