name: Security veracode pipeline scan
on:
  pull_request: # temp, to be removed
  workflow_dispatch:
  schedule:
    - cron: "35 6 * * MON-FRI" # Every weekday

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  package-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Package application
        run: bundle exec veracode prepare
      - name: Rename package zip file
        shell: bash
        run: mv tmp/veracode*.zip ./source.zip
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: veracode-package-${{ github.sha }}
          path: source.zip
          retention-days: 1

  security-veracode-pipeline-scan:
    name: Project security veracode pipeline scan
    needs: package-application
    uses: ./.github/workflows/test_custom_veracode_scan.yml
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      veracode_package_artifact_name: veracode-package-${{ github.sha }}
    secrets: inherit
